"""add_language_requirements_to_jobs

Revision ID: 714b6ed09373
Revises: 516183b53f0a
Create Date: 2026-03-11 18:24:35.157266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '714b6ed09373'
down_revision: Union[str, None] = '516183b53f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('language_requirements', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'language_requirements')
    # ### end Alembic commands ###
