"""simplify_linkedin_searches_ai_powered

Revision ID: 8ec1667ba329
Revises: a1b2c3d4e5f6
Create Date: 2026-03-11 14:22:48.694702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ec1667ba329'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_searches', 'remote_options')
    op.drop_column('linkedin_searches', 'fair_chance_employer')
    op.drop_column('linkedin_searches', 'has_verifications')
    op.drop_column('linkedin_searches', 'sort_by')
    op.drop_column('linkedin_searches', 'benefits')
    op.drop_column('linkedin_searches', 'under_10_applicants')
    op.drop_column('linkedin_searches', 'easy_apply')
    op.drop_column('linkedin_searches', 'experience_levels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_searches', sa.Column('experience_levels', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.add_column('linkedin_searches', sa.Column('easy_apply', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('linkedin_searches', sa.Column('under_10_applicants', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('linkedin_searches', sa.Column('benefits', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.add_column('linkedin_searches', sa.Column('sort_by', sa.VARCHAR(length=10), server_default=sa.text("'DD'::character varying"), autoincrement=False, nullable=False))
    op.add_column('linkedin_searches', sa.Column('has_verifications', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('linkedin_searches', sa.Column('fair_chance_employer', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('linkedin_searches', sa.Column('remote_options', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
