"""add_logic_group_to_filter_rules

Revision ID: a846a5266c70
Revises: a9e48ae82445
Create Date: 2026-03-11 19:02:55.425723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a846a5266c70'
down_revision: Union[str, None] = 'a9e48ae82445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter_rules', sa.Column('logic_group', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    # ### end Alembic commands ###

    # Data migration: set existing title/description rules to logic_group='all'
    op.execute(
        "UPDATE filter_rules SET logic_group = 'all' "
        "WHERE value LIKE 'title:%' OR value LIKE 'description:%'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter_rules', 'logic_group')
    # ### end Alembic commands ###
